disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace

identifier_name:
  min_length: 2 # only min_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
